"""Project-level datasource authoring and management API."""

from __future__ import annotations

from marivo.datasource.authoring import (
    DatasourceRef,
    clickhouse,
    duckdb,
    mysql,
    postgres,
    ref,
    trino,
)
from marivo.datasource.catalog import DatasourceCatalog, load
from marivo.datasource.discover import (
    discover_dimension_values,
    discover_dimensions,
    discover_entity,
    discover_measures,
    discover_relationship,
    discover_time_dimensions,
)
from marivo.datasource.discovery import (
    DimensionDiscoveryResult,
    DimensionValueDiscoveryResult,
    DimensionValueFact,
    DiscoveryEvidenceEntry,
    DiscoveryIssue,
    DiscoverySignal,
    EntityDiscoveryResult,
    MeasureDiscoveryResult,
    RawSqlResult,
    RelationshipDiscoveryResult,
    SemanticJudgmentTarget,
    TimeDimensionDiscoveryResult,
    TimeValueRange,
)
from marivo.datasource.help import help, help_text
from marivo.datasource.manage import (
    DatasourceDescription,
    DatasourceList,
    DatasourceSummary,
    DatasourceTestResult,
    connect,
    describe,
    list,
    preview,
    raw_sql,
    register,
    remove,
    test,
)
from marivo.datasource.metadata import TableMetadata
from marivo.datasource.scan import (
    JoinSide,
    ScanScope,
    TableSource,
    csv,
    latest_partition,
    parquet,
    partition,
    table,
    unpruned,
)
from marivo.preview import PreviewResult

__all__ = [
    "DatasourceCatalog",
    "DatasourceDescription",
    "DatasourceList",
    "DatasourceRef",
    "DatasourceSummary",
    "DatasourceTestResult",
    "DimensionDiscoveryResult",
    "DimensionValueDiscoveryResult",
    "DimensionValueFact",
    "DiscoveryEvidenceEntry",
    "DiscoveryIssue",
    "DiscoverySignal",
    "EntityDiscoveryResult",
    "JoinSide",
    "MeasureDiscoveryResult",
    "PreviewResult",
    "RawSqlResult",
    "RelationshipDiscoveryResult",
    "ScanScope",
    "SemanticJudgmentTarget",
    "TableMetadata",
    "TableSource",
    "TimeDimensionDiscoveryResult",
    "TimeValueRange",
    "clickhouse",
    "connect",
    "csv",
    "describe",
    "discover_dimension_values",
    "discover_dimensions",
    "discover_entity",
    "discover_measures",
    "discover_relationship",
    "discover_time_dimensions",
    "duckdb",
    "help",
    "help_text",
    "latest_partition",
    "list",
    "load",
    "mysql",
    "parquet",
    "partition",
    "postgres",
    "preview",
    "raw_sql",
    "ref",
    "register",
    "remove",
    "table",
    "test",
    "trino",
    "unpruned",
]
