"""Project-level datasource authoring and management API."""

from __future__ import annotations

from marivo.datasource.authoring import (
    ClickHouseSpec,
    DatasourceRef,
    DatasourceSpec,
    DuckDBSpec,
    MySQLSpec,
    PostgresSpec,
    TrinoSpec,
    clickhouse,
    duckdb,
    mysql,
    postgres,
    ref,
    trino,
)
from marivo.datasource.catalog import DatasourceCatalog, load
from marivo.datasource.discover import (
    discover_dimension_values,
    discover_dimensions,
    discover_entity,
    discover_measures,
    discover_relationship,
    discover_time_dimensions,
)
from marivo.datasource.discovery import (
    DatasourceResult,
)
from marivo.datasource.help import help, help_text
from marivo.datasource.manage import (
    DatasourceConnection,
    DatasourceDescription,
    DatasourceList,
    DatasourceSummary,
    DatasourceTestResult,
    connect,
    describe,
    inspect_partitions,
    inspect_table,
    list,
    preview,
    raw_sql,
    register,
    remove,
    test,
)
from marivo.datasource.metadata import TableMetadata
from marivo.datasource.scan import (
    JoinSide,
    ScanScope,
    TableSource,
    csv,
    parquet,
    partition,
    table,
    unpruned,
)
from marivo.preview import PreviewResult

__all__ = [
    "ClickHouseSpec",
    "DatasourceCatalog",
    "DatasourceConnection",
    "DatasourceDescription",
    "DatasourceList",
    "DatasourceRef",
    "DatasourceResult",
    "DatasourceSpec",
    "DatasourceSummary",
    "DatasourceTestResult",
    "DuckDBSpec",
    "JoinSide",
    "MySQLSpec",
    "PostgresSpec",
    "PreviewResult",
    "ScanScope",
    "TableMetadata",
    "TableSource",
    "TrinoSpec",
    "clickhouse",
    "connect",
    "csv",
    "describe",
    "discover_dimension_values",
    "discover_dimensions",
    "discover_entity",
    "discover_measures",
    "discover_relationship",
    "discover_time_dimensions",
    "duckdb",
    "help",
    "help_text",
    "inspect_partitions",
    "inspect_table",
    "list",
    "load",
    "mysql",
    "parquet",
    "partition",
    "postgres",
    "preview",
    "raw_sql",
    "ref",
    "register",
    "remove",
    "table",
    "test",
    "trino",
    "unpruned",
]
