"""Pin the public ``__all__`` of each marivo surface module.

Any added or removed public symbol must be a deliberate edit here.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys

import marivo.analysis as ma
import marivo.datasource as md
import marivo.semantic as ms

SEMANTIC_PUBLIC = {
    "AggregateFoldInput",
    "AggregateFoldValue",
    "AiContextValue",
    "CalendarLevelDetails",
    "BusinessOrderDetails",
    "BusinessOrderEntry",
    "BusinessOrderKind",
    "CalendarPeriodPage",
    "CatalogCollection",
    "CatalogEntry",
    "DatasourceEntry",
    "DatasourceDetails",
    "DerivedMetricDetails",
    "DimensionEntry",
    "DimensionDetails",
    "DomainEntry",
    "DomainDetails",
    "EntityEntry",
    "EntityDetails",
    "EventDetails",
    "EventPrecedence",
    "EventSequence",
    "EventEntry",
    "GrainToDate",
    "Inception",
    "JoinKey",
    "LifecycleState",
    "MeasureEntry",
    "MeasureDetails",
    "MetricEntry",
    "MetricDetails",
    "ModelStateHandle",
    "Participant",
    "ParticipantRoleHandle",
    "PeriodCalendarDetails",
    "PeriodCalendarEntry",
    "PeriodCalendarKind",
    "TemporalSetKind",
    "PeriodCorrespondence",
    "PreviewBatchResult",
    "ReadinessInputSummary",
    "ReadinessIssue",
    "ReadinessReport",
    "Ref",
    "RelationshipEntry",
    "RelationshipDetails",
    "RichnessReport",
    "SemanticCatalog",
    "SemanticKind",
    "SimpleMetricDetails",
    "SourceCheck",
    "SourceHealthCheckResult",
    "SourceHealthReport",
    "StateModelDetails",
    "StateModelEntry",
    "StateTransition",
    "TemporalOccurrencePage",
    "TemporalSetDetails",
    "TemporalSetEntry",
    "WorkScheduleDetails",
    "WorkScheduleEntry",
    "WorkScheduleKind",
    "TimeDimensionEntry",
    "TimeDimensionDetails",
    "aggregate",
    "ai_context",
    "all_rows",
    "bind",
    "business_order",
    "calendar_grain",
    "count",
    "cumulative",
    "datetime",
    "dimension",
    "dimension_column",
    "domain",
    "entity",
    "errors",
    "event",
    "event_sequence",
    "grain_to_date",
    "hour_prefix",
    "inception",
    "join_on",
    "linear",
    "lifecycle_state",
    "load",
    "measure",
    "measure_column",
    "metric",
    "model_state",
    "participant",
    "participant_role",
    "period_calendar",
    "period_correspondence",
    "precedes",
    "temporal_set",
    "ratio",
    "ref",
    "additive",
    "additive_all",
    "non_additive",
    "nulls",
    "empty",
    "zero_denominator",
    "relationship",
    "richness",
    "snapshot",
    "source_check",
    "state_model",
    "strptime",
    "time_dimension",
    "time_dimension_column",
    "timestamp",
    "trailing",
    "transition",
    "typing",
    "validity",
    "weighted_mean",
    "where",
    "work_schedule",
}

ANALYSIS_PUBLIC = {
    "AllInstances",
    "AnalysisAction",
    "AnalysisContract",
    "AnyAnchor",
    "AnyInstance",
    "ArtifactDigest",
    "ArtifactRef",
    "ArtifactRevalidation",
    "ArtifactSummary",
    "AtLeast",
    "BeforeEndBoundary",
    "BoundedCompletenessDeclarationV1",
    "CalendarWindow",
    "CohortContrast",
    "CountMethod",
    "DatasetByteCount",
    "DroppedBefore",
    "Duration",
    "ElapsedWindow",
    "EmptyOpportunityPolicy",
    "EventPattern",
    "EveryAnchor",
    "EveryStart",
    "EvidenceIntegrityError",
    "ExactKeys",
    "FailedRun",
    "Finding",
    "FindingPage",
    "FirstPerSubject",
    "ForecastHorizon",
    "ForecastModel",
    "FromInception",
    "FunnelLossRate",
    "Grain",
    "GridEndpoint",
    "GridWindow",
    "GroupedAnalysisDomain",
    "GroupedNumericRelation",
    "GroupedRatioRelation",
    "GroupedStatisticRelation",
    "InState",
    "IncompleteRun",
    "LogicalAnalysisDomain",
    "LogicalAnchorDomain",
    "LogicalAssociationResult",
    "LogicalAttributionResult",
    "LogicalBooleanRelation",
    "LogicalCategoryRelation",
    "LogicalCoefficientRelation",
    "LogicalCoefficientSelectionRelation",
    "LogicalCompletedJourneys",
    "LogicalDeviationResult",
    "LogicalDifferenceRelation",
    "LogicalDwellSummary",
    "LogicalEventDurationResult",
    "LogicalFixedAnalysisDomain",
    "LogicalForecastResult",
    "LogicalFunnelComparisonResult",
    "LogicalFunnelResult",
    "LogicalHistoryResult",
    "LogicalJourneyResult",
    "LogicalNumericRelation",
    "LogicalRankingResult",
    "LogicalRatioRelation",
    "LogicalRetentionResult",
    "LogicalRolledNumericRelation",
    "LogicalRolledRatioRelation",
    "LogicalSelectedBooleanRelation",
    "LogicalSelectedCategoryRelation",
    "LogicalSelectedDifferenceRelation",
    "LogicalSelectedNumericRelation",
    "LogicalSelectedTemporalRelation",
    "LogicalStateDistributionResult",
    "LogicalStateIntervalResult",
    "LogicalStatisticRelation",
    "LogicalSubjectRetentionResult",
    "LogicalTable",
    "LogicalTemporalRelation",
    "LogicalTimeAnalysisDomain",
    "LogicalTimeRunResult",
    "LogicalTransitionSummary",
    "LogicalViolationResult",
    "MaterializedAnalysisDomain",
    "MaterializedAnchorDomain",
    "MaterializedAssociationResult",
    "MaterializedAttributionResult",
    "MaterializedBooleanRelation",
    "MaterializedCategoryRelation",
    "MaterializedCoefficientRelation",
    "MaterializedCoefficientSelectionRelation",
    "MaterializedCompletedJourneys",
    "MaterializedDatasetState",
    "MaterializedDeviationResult",
    "MaterializedDifferenceRelation",
    "MaterializedDwellSummary",
    "MaterializedEventDurationResult",
    "MaterializedForecastResult",
    "MaterializedFunnelComparisonResult",
    "MaterializedFunnelResult",
    "MaterializedGroupedNumericRelation",
    "MaterializedHistoryResult",
    "MaterializedJourneyResult",
    "MaterializedNumericRelation",
    "MaterializedRankingResult",
    "MaterializedRatioRelation",
    "MaterializedRetentionResult",
    "MaterializedRolledNumericRelation",
    "MaterializedRolledRatioRelation",
    "MaterializedSelectedBooleanRelation",
    "MaterializedSelectedCategoryRelation",
    "MaterializedSelectedDifferenceRelation",
    "MaterializedSelectedNumericRelation",
    "MaterializedSelectedTemporalRelation",
    "MaterializedStateDistributionResult",
    "MaterializedStateIntervalResult",
    "MaterializedStatisticRelation",
    "MaterializedSubjectRetentionResult",
    "MaterializedTable",
    "MaterializedTemporalRelation",
    "MaterializedTimeAnalysisDomain",
    "MaterializedTimeRunResult",
    "MaterializedTransitionSummary",
    "MaterializedViolationResult",
    "OneToOneCorrespondence",
    "PatternStep",
    "PeriodChange",
    "ReferenceWeights",
    "RootRoute",
    "RootRoutes",
    "RowMethod",
    "RunPage",
    "Session",
    "SessionGraph",
    "SourceOriginCompletenessDeclarationV1",
    "SubjectBinding",
    "SucceededRun",
    "TimeChange",
    "TimeGrid",
    "TimeScope",
    "UnionKeys",
    "WindowBucketAlignment",
    "all_instances",
    "all_of",
    "any_anchor",
    "any_instance",
    "any_of",
    "at_least",
    "calendar_days",
    "count",
    "count_defined",
    "drift",
    "dropped_before",
    "duration",
    "elapsed",
    "empty_opportunity",
    "every_anchor",
    "every_start",
    "first_per_subject",
    "from_inception",
    "funnel_loss_rate",
    "grain",
    "in_state",
    "max",
    "mean",
    "min",
    "naive",
    "not_",
    "one_to_one",
    "periods",
    "reference_weights",
    "route",
    "routes",
    "runtime_metric",
    "seasonal_naive",
    "sequence",
    "session",
    "step",
    "sum",
    "table",
    "time_grid",
    "time_scope",
    "window_bucket",
}

ANALYSIS_PUBLIC_ORDER_SHA256 = "5fcf75a0978f104772776d5d6561226348365675f075fd9b74347cdb8d7e151d"

DATASOURCE_PUBLIC = {
    "ClickHouseSpec",
    "DatasourceCatalog",
    "DatasourceDescription",
    "DatasourceFailure",
    "DatasourceList",
    "DatasourceSpec",
    "DatasourceSummary",
    "DatasourceTestResult",
    "DiscoverySnapshot",
    "DuckDBSpec",
    "ExecutionCapabilities",
    "MySQLSpec",
    "PartitionInspection",
    "PartitionScope",
    "Partitioning",
    "PhysicalExtent",
    "PostgresSpec",
    "SourceInspection",
    "SQLiteSpec",
    "TableSource",
    "TrinoSpec",
    "UnprunedScope",
    "clickhouse",
    "csv",
    "describe",
    "duckdb",
    "inspect",
    "json",
    "list",
    "load",
    "mysql",
    "partition",
    "parquet",
    "postgres",
    "raw_sql",
    "register",
    "remove",
    "source_param",
    "sqlite",
    "table",
    "test",
    "time_range",
    "trino",
    "unpruned",
}


def test_partition_scope_constructor_signature_is_stable() -> None:
    import inspect

    import marivo.datasource as md

    assert str(inspect.signature(md.PartitionScope)) == (
        "(values: 'tuple[tuple[str, str], ...]', max_rows: 'int', timeout_seconds: 'int') -> None"
    )


def test_top_level_package_does_not_add_public_convenience_exports() -> None:
    script = (
        "import json, marivo; "
        "print(json.dumps(sorted(name for name in dir(marivo) "
        "if name == '__version__' or not name.startswith('_'))))"
    )
    result = subprocess.run(
        [sys.executable, "-c", script],
        capture_output=True,
        check=False,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert json.loads(result.stdout) == ["__version__", "help"]


def test_semantic_all_is_pinned() -> None:
    assert set(ms.__all__) == SEMANTIC_PUBLIC


def test_analysis_all_is_pinned() -> None:
    assert set(ma.__all__) == ANALYSIS_PUBLIC


def test_analysis_all_order_is_pinned() -> None:
    payload = json.dumps(ma.__all__, ensure_ascii=True, separators=(",", ":"))

    assert hashlib.sha256(payload.encode("utf-8")).hexdigest() == ANALYSIS_PUBLIC_ORDER_SHA256


def test_phase2_datasource_all_is_pinned_to_the_baseline() -> None:
    assert set(md.__all__) == DATASOURCE_PUBLIC


def test_followup_action_is_not_public_analysis_api() -> None:
    assert "FollowupAction" not in ma.__all__
    assert not hasattr(ma, "FollowupAction")


def test_run_query_stays_nested_under_terminal_runs() -> None:
    assert "RunQuery" not in ma.__all__
    assert not hasattr(ma, "RunQuery")
