"""Pin the public ``__all__`` of each marivo surface module.

Any added or removed public symbol must be a deliberate edit here.
See docs/superpowers/specs/2026-06-13-agent-result-surface-design.md.
"""

from __future__ import annotations

import marivo.analysis as ma
import marivo.datasource as md
import marivo.semantic as ms

SEMANTIC_PUBLIC = {
    "AiContext",
    "AiContextView",
    "AssessmentIssue",
    "AuthoringAssessment",
    "AuthoringQuestion",
    "BriefStatus",
    "ComponentFact",
    "CrossEntityMetricBrief",
    "DatasetSource",
    "DatasourceDetails",
    "DecisionRecord",
    "DemandSignal",
    "DerivedMetricBrief",
    "DimensionBrief",
    "DimensionDetails",
    "DimensionRef",
    "DimensionValueFact",
    "DomainBrief",
    "DomainBriefSummary",
    "DomainDetails",
    "DomainRef",
    "EntityBrief",
    "EntityDetails",
    "EntityRef",
    "FileSource",
    "FormatCandidate",
    "JoinPathFact",
    "LadderOrderError",
    "MetricBrief",
    "MetricDetails",
    "MetricRef",
    "ParityResult",
    "PrimaryKeyCandidate",
    "ReadinessInputSummary",
    "ReadinessIssue",
    "ReadinessReport",
    "RegisteredMatch",
    "RichnessReport",
    "RelationshipBrief",
    "RelationshipDetails",
    "RelationshipRef",
    "SemanticCatalog",
    "SemanticKind",
    "SemanticKindInput",
    "SemanticObject",
    "SemanticObjectDetails",
    "SemanticObjectList",
    "SemanticRef",
    "SemanticRefInput",
    "SnapshotVersioning",
    "TableSource",
    "TimeDimensionBrief",
    "TimeDimensionDetails",
    "TimeDimensionRef",
    "ValidityVersioning",
    "VerifyResult",
    "VersioningHints",
    "aggregate",
    "dimension",
    "domain",
    "entity",
    "errors",
    "file",
    "help",
    "help_text",
    "linear",
    "load",
    "parity_check",
    "prepare_cross_entity_metric",
    "prepare_derived_metric",
    "prepare_dimension",
    "prepare_domain",
    "prepare_entity",
    "prepare_metric",
    "prepare_relationship",
    "prepare_time_dimension",
    "ratio",
    "readiness",
    "semi_additive",
    "simple_metric",
    "record_decision",
    "ref",
    "relationship",
    "richness",
    "snapshot",
    "table",
    "time_dimension",
    "typing",
    "validity",
    "verify_object",
    "weighted_average",
}

ANALYSIS_PUBLIC = {
    "AbsoluteWindow",
    "AlignmentKind",
    "AlignmentPolicy",
    "ArtifactRef",
    "AssociationResult",
    "AttributionFrame",
    "BaseFrame",
    "BaseFrameMeta",
    "BlockingIssue",
    "CalendarPolicy",
    "CalendarRef",
    "CandidateObjective",
    "CandidateSet",
    "ComponentFrame",
    "ConfidenceScope",
    "DeltaFrame",
    "DiscoverSensitivity",
    "ExplorationResult",
    "FollowupAction",
    "ForecastFrame",
    "FramePreview",
    "FrameSummary",
    "FrameSummaryEntry",
    "HypothesisTestResult",
    "JobSummary",
    "Lineage",
    "LineageStep",
    "MetricFrame",
    "PromotionPolicy",
    "PromotionSemanticAnchors",
    "QualityReport",
    "ReportRegistration",
    "SamplingPolicy",
    "SemanticObject",
    "SemanticRef",
    "Session",
    "SessionSummary",
    "SlicePredicate",
    "SlicePredicateOp",
    "SliceScalar",
    "SliceValue",
    "TimeScope",
    "TimeScopeInput",
    "errors",
    "evidence",
    "frames",
    "help",
    "help_text",
    "publish",
    "session",
}

DATASOURCE_PUBLIC = {
    "AiContextIR",
    "ColumnInspection",
    "ColumnMetadata",
    "ColumnProfile",
    "DatasourceAiContextIR",
    "DatasourceCatalog",
    "DatasourceConnectionService",
    "DatasourceDescription",
    "DatasourceIR",
    "DatasourceRef",
    "DatasourceSourceLocation",
    "DatasourceSpec",
    "DatasourceSummary",
    "DatasourceTestResult",
    "JoinKeyProbe",
    "JoinSide",
    "MetadataWarning",
    "PartitionMetadata",
    "PreviewResult",
    "PreviewSamplePolicy",
    "PreviewWarning",
    "ScanReport",
    "ScanScope",
    "TableMetadata",
    "connect",
    "datasource",
    "describe",
    "file",
    "help",
    "help_text",
    "inspect_columns",
    "inspect_source",
    "inspect_table",
    "list",
    "load",
    "preview",
    "probe_join_keys",
    "ref",
    "register",
    "remove",
    "table",
    "test",
}


def test_semantic_all_is_pinned() -> None:
    assert set(ms.__all__) == SEMANTIC_PUBLIC


def test_analysis_all_is_pinned() -> None:
    assert set(ma.__all__) == ANALYSIS_PUBLIC


def test_datasource_all_is_pinned() -> None:
    assert set(md.__all__) == DATASOURCE_PUBLIC
