"""Semantic layer API models.

This package provides Pydantic models for the Marivo HTTP API.

Modules:
- base: Shared types, validators, and base classes
- osi: OSI core models (Dimension, Field, Dataset, Relationship, Metric, SemanticModel, OSIDocument)
- marivo_extensions: MARIVO extension models
- intents: Typed intent request models (observe, compare, detect, etc.)
- session: Session management request models
- calendar: Calendar data models
- _infrastructure: Infrastructure configuration models (datasource, routing, etc.)
"""

# Infrastructure models (datasource, routing, steps, signals, etc.)
from ._infrastructure import (
    AggregateQueryStep,
    AnalysisTimeOverride,
    # Approval models
    ApprovalCreateRequest,
    ApprovalDecisionRequest,
    AttributeChangeStep,
    AutoFlagRequest,
    ColumnPropertiesUpdateRequest,
    # Datasource models
    DatasourceDeleteResponse,
    DatasourcePolicyPayload,
    DatasourcePolicyResponse,
    DatasourceRegisterRequest,
    DatasourceResponse,
    DatasourceUpdateRequest,
    GovernanceCheckRequest,
    # Job models
    JobSubmitRequest,
    Measure,
    # Step models
    MetricQueryStep,
    ModifyStepOperation,
    PartitionPruningOverride,
    PlanPatchRequest,
    # Policy models
    PolicyCreateRequest,
    PolicyUpdateRequest,
    QualityRuleCreateRequest,
    ReadinessSignal,
    RouteCapabilityProfileResponse,
    RouteEngineResponse,
    RouteIntentRequest,
    # Routing models
    RouteResolveRequest,
    RouteResolveResponse,
    Scope,
    SyncSelectionItem,
    SyncSelectionRequest,
    TimeAxis,
    TimeScope,
    # Time scope models
    TimeWindow,
)
from .base import (
    AdditivityConstraints,
    AggregationMethod,
    AggregationScope,
    # Base models
    ApiErrorDetail,
    BindingRole,
    BindingScope,
    BlockingRequirement,
    Cardinality,
    CardinalityToParent,
    CarrierKind,
    CatalogMetadata,
    ConsumptionBehavior,
    ConsumptionPolicyType,
    ContextKind,
    ContractMode,
    DescriptorCardinality,
    DimensionDomainKind,
    DimensionValueType,
    DomainCatalogStatus,
    EntityKind,
    EnumValueType,
    HierarchyType,
    HorizonSpec,
    IdStability,
    InferentialSampleSummary,
    JoinKind,
    LifecycleStatus,
    ListResponseBase,
    MembershipCardinality,
    MetricFamily,
    NullabilityPolicy,
    NullableKeyPolicy,
    ObjectHeaderBase,
    ObjectListItemBase,
    ObjectResponseBase,
    ObjectStatus,
    OwnershipSemantics,
    PopulationSpec,
    PredicateOperator,
    PredicateTimePolicy,
    PredicateUsage,
    ProcessType,
    ProfileKind,
    ProfileSchemaVersion,
    ProfileSubjectKind,
    ReadinessStatus,
    RepeatedValuePolicy,
    SampleKind,
    SemanticRef,
    SemanticRole,
    SemanticValidateActionResponse,
    SemanticValidationSummary,
    StateSpec,
    StepSpec,
    StructureKind,
    SubjectCardinality,
    TargetKind,
    TimeGranularity,
    TimeSemanticRole,
    # Literal types
    UniquenessScope,
    ValueSemantics,
    WindowOffset,
    WindowSpec,
    validate_contract_version,
    # Validators
    validate_ref_prefix,
)

# Calendar models
from .calendar import (
    CalendarDataLoadRequest,
    CalendarDataLoadResponse,
    CalendarDataRow,
    CalendarVersionItem,
)

# Catalog models (stub)
from .catalog import (
    CatalogAssetDetail,
    CatalogAssetSearchResult,
    CatalogCalendarPolicyDetail,
    CatalogCalendarPolicySearchResult,
    CatalogEntityDetail,
    CatalogGenericSemanticDetail,
    CatalogMetricDetail,
    CatalogObjectDetail,
    CatalogSearchResult,
    CatalogSemanticSearchResult,
    SourceObjectResponse,
)

# Intent API models
from .intents import (
    ArtifactRef,
    AttributeObservationInput,
    AttributeRequest,
    CompareRequest,
    CorrelateObservationRef,
    CorrelateRequest,
    DecomposeRequest,
    DetectRequest,
    DetectTimeScope,
    DiagnoseRequest,
    ForecastRequest,
    HypothesisContract,
    IntentTestRequest,
    ObservationRef,
    ObserveRequest,
    ObserveScope,
    ObserveTimeScope,
    ObserveTimeScopeAsOf,
    ObserveTimeScopeLatestAvailable,
    ObserveTimeScopeRange,
    ObserveTimeScopeSnapshotNow,
    TestObservationRef,
    ValidateHypothesis,
    ValidateObservationInput,
    ValidateRequest,
)

# MARIVO extension models
from .marivo_extensions import (
    MarivoAdditivity,
    MarivoDatasetExtension,
    MarivoFieldExtension,
    MarivoMetricExtension,
    MarivoMetricFilter,
    MarivoRelationshipExtension,
    MarivoSemanticModelExtension,
)

# OSI core models
from .osi import (
    AIContext,
    CustomExtension,
    Dataset,
    DialectExpression,
    Dimension,
    Expression,
    Field,
    Metric,
    OSIDocument,
    Relationship,
    SemanticModel,
)

# Session models
from .session import (
    SessionCreateRequest,
    SessionStateQueryRequest,
    SessionTerminateRequest,
)

__all__ = [  # noqa: RUF022
    "AdditivityConstraints",
    "AggregateQueryStep",
    "AggregationMethod",
    "AggregationScope",
    "AIContext",
    "AnalysisTimeOverride",
    "ApiErrorDetail",
    "ApprovalCreateRequest",
    "ApprovalDecisionRequest",
    "ArtifactRef",
    "AttributeChangeStep",
    "AttributeObservationInput",
    "AttributeRequest",
    "AutoFlagRequest",
    "BlockingRequirement",
    "BindingRole",
    "BindingScope",
    "CalendarDataRow",
    "CalendarDataLoadRequest",
    "CalendarDataLoadResponse",
    "CalendarVersionItem",
    "CatalogAssetDetail",
    "CatalogAssetSearchResult",
    "CatalogCalendarPolicyDetail",
    "CatalogCalendarPolicySearchResult",
    "CatalogEntityDetail",
    "CatalogGenericSemanticDetail",
    "CatalogMetricDetail",
    "CatalogObjectDetail",
    "CatalogSearchResult",
    "CatalogSemanticSearchResult",
    "Cardinality",
    "CardinalityToParent",
    "CatalogMetadata",
    "CarrierKind",
    "ColumnPropertiesUpdateRequest",
    "CompareRequest",
    "ConsumptionBehavior",
    "ConsumptionPolicyType",
    "ContextKind",
    "ContractMode",
    "CorrelateObservationRef",
    "CorrelateRequest",
    "CustomExtension",
    "DatasourceDeleteResponse",
    "DatasourcePolicyPayload",
    "DatasourcePolicyResponse",
    "DatasourceRegisterRequest",
    "DatasourceResponse",
    "DatasourceUpdateRequest",
    "DecomposeRequest",
    "DescriptorCardinality",
    "DetectRequest",
    "DetectTimeScope",
    "DiagnoseRequest",
    "Dimension",
    "DimensionDomainKind",
    "DimensionValueType",
    "DomainCatalogStatus",
    "Dataset",
    "DialectExpression",
    "EntityKind",
    "EnumValueType",
    "Expression",
    "Field",
    "ForecastRequest",
    "GovernanceCheckRequest",
    "HierarchyType",
    "HorizonSpec",
    "HypothesisContract",
    "IdStability",
    "InferentialSampleSummary",
    "IntentTestRequest",
    "JobSubmitRequest",
    "JoinKind",
    "LifecycleStatus",
    "ListResponseBase",
    "MarivoAdditivity",
    "MarivoDatasetExtension",
    "MarivoFieldExtension",
    "MarivoMetricExtension",
    "MarivoMetricFilter",
    "MarivoRelationshipExtension",
    "MarivoSemanticModelExtension",
    "Measure",
    "MembershipCardinality",
    "Metric",
    "MetricFamily",
    "MetricQueryStep",
    "ModifyStepOperation",
    "NullabilityPolicy",
    "NullableKeyPolicy",
    "ObjectHeaderBase",
    "ObjectListItemBase",
    "ObjectResponseBase",
    "ObjectStatus",
    "ObservationRef",
    "ObserveRequest",
    "ObserveScope",
    "ObserveTimeScope",
    "ObserveTimeScopeAsOf",
    "ObserveTimeScopeLatestAvailable",
    "ObserveTimeScopeRange",
    "ObserveTimeScopeSnapshotNow",
    "OSIDocument",
    "OwnershipSemantics",
    "PartitionPruningOverride",
    "PopulationSpec",
    "PredicateOperator",
    "PredicateTimePolicy",
    "PredicateUsage",
    "PlanPatchRequest",
    "PolicyCreateRequest",
    "PolicyUpdateRequest",
    "ProcessType",
    "ProfileKind",
    "ProfileSchemaVersion",
    "ProfileSubjectKind",
    "QualityRuleCreateRequest",
    "ReadinessSignal",
    "ReadinessStatus",
    "Relationship",
    "RepeatedValuePolicy",
    "RouteCapabilityProfileResponse",
    "RouteEngineResponse",
    "RouteIntentRequest",
    "RouteResolveRequest",
    "RouteResolveResponse",
    "SampleKind",
    "Scope",
    "SemanticModel",
    "SemanticRef",
    "SemanticValidateActionResponse",
    "SemanticValidationSummary",
    "SemanticRole",
    "SessionCreateRequest",
    "SessionStateQueryRequest",
    "SessionTerminateRequest",
    "SourceObjectResponse",
    "StateSpec",
    "StepSpec",
    "StructureKind",
    "SubjectCardinality",
    "SyncSelectionItem",
    "SyncSelectionRequest",
    "TargetKind",
    "TestObservationRef",
    "TimeAxis",
    "TimeGranularity",
    "TimeScope",
    "TimeSemanticRole",
    "TimeWindow",
    "UniquenessScope",
    "ValidateHypothesis",
    "ValidateObservationInput",
    "ValidateRequest",
    "ValueSemantics",
    "WindowOffset",
    "WindowSpec",
    "validate_contract_version",
    "validate_ref_prefix",
]
