"""Semantic layer API models.

This package provides Pydantic models for the Marivo HTTP API,
implementing the typed semantic contracts defined in docs/semantic/*.md.

Modules:
- base: Shared types, validators, and base classes
- time: Time semantic objects
- enum_set: Enum value set objects
- dimension: Dimension objects
- entity: Entity objects
- process_object: Process object models (experiments, cohorts, funnels, etc.)
- metric: Metric v2 models with 7 family types
- binding: Typed binding models
- compatibility_profile: Compiler compatibility profile models
- predicate: Predicate filter semantic object models
- intents: Typed intent request models (observe, compare, detect, etc.)
- session: Session management request models
- _infrastructure: Infrastructure configuration models (datasource, routing, etc.)
"""

# Infrastructure models (datasource, routing, steps, signals, etc.)
from ._infrastructure import (
    AggregateQueryStep,
    AnalysisTimeOverride,
    # Approval models
    ApprovalCreateRequest,
    ApprovalDecisionRequest,
    AttributeChangeStep,
    AutoFlagRequest,
    ColumnPropertiesUpdateRequest,
    # Datasource models
    DatasourceDeleteResponse,
    DatasourcePolicyPayload,
    DatasourcePolicyResponse,
    DatasourceRegisterRequest,
    DatasourceResponse,
    DatasourceUpdateRequest,
    GovernanceCheckRequest,
    # Job models
    JobSubmitRequest,
    Measure,
    # Step models
    MetricQueryStep,
    ModifyStepOperation,
    PartitionPruningOverride,
    PlanPatchRequest,
    # Policy models
    PolicyCreateRequest,
    PolicyUpdateRequest,
    QualityRuleCreateRequest,
    ReadinessSignal,
    RouteCapabilityProfileResponse,
    RouteEngineResponse,
    RouteIntentRequest,
    # Routing models
    RouteResolveRequest,
    RouteResolveResponse,
    Scope,
    SyncSelectionItem,
    SyncSelectionRequest,
    TimeAxis,
    TimeScope,
    # Time scope models
    TimeWindow,
)
from .base import (
    AdditivityConstraints,
    AggregationMethod,
    AggregationScope,
    # Base models
    ApiErrorDetail,
    BindingRole,
    BindingScope,
    BlockingRequirement,
    Cardinality,
    CardinalityToParent,
    CarrierKind,
    CatalogMetadata,
    ConsumptionBehavior,
    ConsumptionPolicyType,
    ContextKind,
    ContractMode,
    DescriptorCardinality,
    DimensionDomainKind,
    DimensionValueType,
    DomainCatalogStatus,
    EntityKind,
    EnumValueType,
    HierarchyType,
    HorizonSpec,
    IdStability,
    InferentialSampleSummary,
    JoinKind,
    LifecycleStatus,
    ListResponseBase,
    MembershipCardinality,
    MetricFamily,
    NullabilityPolicy,
    NullableKeyPolicy,
    ObjectHeaderBase,
    ObjectListItemBase,
    ObjectResponseBase,
    ObjectStatus,
    OwnershipSemantics,
    PopulationSpec,
    PredicateOperator,
    PredicateTimePolicy,
    PredicateUsage,
    ProcessType,
    ProfileKind,
    ProfileSchemaVersion,
    ProfileSubjectKind,
    ReadinessStatus,
    RepeatedValuePolicy,
    SampleKind,
    SemanticRef,
    SemanticRole,
    SemanticValidateActionResponse,
    SemanticValidationSummary,
    StateSpec,
    StepSpec,
    StructureKind,
    SubjectCardinality,
    TargetKind,
    TimeGranularity,
    TimeSemanticRole,
    # Literal types
    UniquenessScope,
    ValueSemantics,
    WindowOffset,
    WindowSpec,
    validate_contract_version,
    # Validators
    validate_ref_prefix,
)

# Binding models
from .binding import (
    BindingCoverageAddition,
    BindingDeriveRevisionRequest,
    BindingHeader,
    BindingImport,
    BindingInterfaceContract,
    BindingTarget,
    CarrierBinding,
    ConsumptionPolicySpec,
    FieldBinding,
    FieldSurfaceSpec,
    JoinRelation,
    TypedBindingCreateRequest,
    TypedBindingListItem,
    TypedBindingListResponse,
    TypedBindingResponse,
    TypedBindingUpdateRequest,
)
from .catalog import (
    CatalogAssetDetail,
    CatalogAssetSearchResult,
    CatalogCalendarPolicyDetail,
    CatalogCalendarPolicySearchResult,
    CatalogEntityDetail,
    CatalogGenericSemanticDetail,
    CatalogMetricDetail,
    CatalogObjectDetail,
    CatalogSearchResult,
    CatalogSemanticSearchResult,
    SourceObjectResponse,
)

# Compatibility Profile models
from .compatibility_profile import (
    CompatibilityProfileCreateRequest,
    CompatibilityProfileListItem,
    CompatibilityProfileListResponse,
    CompatibilityProfileResponse,
    CompatibilityProfileUpdateRequest,
    EntityRelationshipCreateRequest,
    EntityRelationshipListItem,
    EntityRelationshipListResponse,
    EntityRelationshipResponse,
    EntityRelationshipUpdateRequest,
    FieldProfileRequirement,
    GovernancePreflightRequirement,
    ProcessCapability,
    ProcessRequirement,
    ProfileAggregationCompatibility,
    ProfileGrainCompatibility,
    ProfileTimeCompatibility,
    ProfileTrace,
    RelationshipGrainCompatibility,
    RelationshipKeyAlignment,
    RelationshipTimeAlignment,
    SnapshotEffectiveWindowAlignment,
)

# Dimension models
from .dimension import (
    DimensionCreateRequest,
    DimensionGroupingContract,
    DimensionHeader,
    DimensionHierarchySpec,
    DimensionInterfaceContract,
    DimensionListItem,
    DimensionListResponse,
    DimensionListResponseFull,
    DimensionResponse,
    DimensionUpdateRequest,
    DimensionValueDomainSpec,
    TimeDerivedRequirementSpec,
)
from .domain import (
    DomainCatalogCreateRequest,
    DomainCatalogListResponse,
    DomainCatalogResponse,
    DomainCatalogUpdateRequest,
    DomainSemanticObjectSearchItem,
    DomainSemanticObjectSearchResponse,
)

# Entity models
from .entity import (
    EntityBindingSpec,
    EntityFieldSpec,
    EntityHeader,
    EntityHierarchySpec,
    EntityIdentitySpec,
    EntityInterfaceContract,
    PhysicalExpressionLocatorSpec,
    StableDescriptorSpec,
    TypedEntityCreateRequest,
    TypedEntityListItem,
    TypedEntityListResponse,
    TypedEntityListResponseFull,
    TypedEntityResponse,
    TypedEntityUpdateRequest,
)

# Enum Set models
from .enum_set import (
    EnumSetCreateRequest,
    EnumSetHeader,
    EnumSetListItem,
    EnumSetListResponse,
    EnumSetResponse,
    EnumSetUpdateRequest,
    EnumSetVersionResponse,
    EnumSetVersionSpec,
    EnumValueSpec,
)

# Intent API models
from .intents import (
    ArtifactRef,
    AttributeObservationInput,
    AttributeRequest,
    CompareRequest,
    CorrelateObservationRef,
    CorrelateRequest,
    DecomposeRequest,
    DetectRequest,
    DetectTimeScope,
    DiagnoseRequest,
    ForecastRequest,
    HypothesisContract,
    IntentTestRequest,
    ObservationRef,
    ObserveRequest,
    ObserveScope,
    ObserveTimeScope,
    ObserveTimeScopeAsOf,
    ObserveTimeScopeLatestAvailable,
    ObserveTimeScopeRange,
    ObserveTimeScopeSnapshotNow,
    TestObservationRef,
    ValidateHypothesis,
    ValidateObservationInput,
    ValidateRequest,
)

# Metric models
from .metric import (
    AverageMetricPayload,
    CountMetricPayload,
    DistributionMetricPayload,
    DistributionSpec,
    MeasurementComponent,
    MetricHeader,
    MetricPayload,
    MetricRevisionCreateRequest,
    RateMetricPayload,
    ScoreMetricPayload,
    SumMetricPayload,
    SurvivalMetricPayload,
    SurvivalSpec,
    TypedMetricCreateRequest,
    TypedMetricListItem,
    TypedMetricListResponse,
    TypedMetricListResponseFull,
    TypedMetricResponse,
    TypedMetricUpdateRequest,
)

# Predicate models
from .predicate import (
    PredicateAtom,
    PredicateConjunction,
    PredicateCreateRequest,
    PredicateHeader,
    PredicateInterfaceContract,
    PredicateListItem,
    PredicateListResponse,
    PredicateListResponseFull,
    PredicatePayload,
    PredicateResponse,
    PredicateUpdateRequest,
)

# Process Object models
from .process_object import (
    CohortDefinitionPayload,
    ContextProcessContract,
    EntityProcessContract,
    ExperimentContextPayload,
    ExperimentSplitBasis,
    ExperimentVariant,
    FunnelDefinitionPayload,
    IdleGapSpec,
    LifecycleStateMachinePayload,
    PathLagSpec,
    PathPatternPayload,
    ProcessInterfaceContract,
    ProcessObjectCreateRequest,
    ProcessObjectHeader,
    ProcessObjectListItem,
    ProcessObjectListResponse,
    ProcessObjectListResponseFull,
    ProcessObjectResponse,
    ProcessObjectUpdateRequest,
    ProcessPayload,
    SessionContractPayload,
    StepGapSpec,
)
from .semantic_batch import (
    SemanticBatchItem,
    SemanticBatchItemResponse,
    SemanticBatchRequest,
    SemanticBatchResponse,
)

# Session models
from .session import (
    SessionCreateRequest,
    SessionStateQueryRequest,
    SessionTerminateRequest,
)

# Time models
from .time import (
    TimeCreateRequest,
    TimeListItem,
    TimeListResponse,
    TimeListResponseFull,
    TimeResponse,
    TimeSemanticHeader,
    TimeSurfaceSpec,
    TimeUpdateRequest,
)

__all__ = [  # noqa: RUF022
    "AdditivityConstraints",
    "AggregateQueryStep",
    "AggregationMethod",
    "AggregationScope",
    "AnalysisTimeOverride",
    "ApiErrorDetail",
    "ApprovalCreateRequest",
    "ApprovalDecisionRequest",
    "ArtifactRef",
    "AttributeChangeStep",
    "AttributeObservationInput",
    "AttributeRequest",
    "AutoFlagRequest",
    "AverageMetricPayload",
    "BlockingRequirement",
    "BindingHeader",
    "BindingImport",
    "BindingInterfaceContract",
    "BindingRole",
    "BindingScope",
    "BindingTarget",
    "CatalogAssetDetail",
    "CatalogAssetSearchResult",
    "CatalogCalendarPolicyDetail",
    "CatalogCalendarPolicySearchResult",
    "CatalogEntityDetail",
    "CatalogGenericSemanticDetail",
    "CatalogMetricDetail",
    "CatalogObjectDetail",
    "CatalogSearchResult",
    "CatalogSemanticSearchResult",
    "Cardinality",
    "CardinalityToParent",
    "CatalogMetadata",
    "CarrierBinding",
    "CarrierKind",
    "CohortDefinitionPayload",
    "ColumnPropertiesUpdateRequest",
    "CompareRequest",
    "CompatibilityProfileCreateRequest",
    "CompatibilityProfileListItem",
    "CompatibilityProfileListResponse",
    "CompatibilityProfileResponse",
    "CompatibilityProfileUpdateRequest",
    "ConsumptionBehavior",
    "ConsumptionPolicySpec",
    "ConsumptionPolicyType",
    "ContextKind",
    "ContextProcessContract",
    "ContractMode",
    "CorrelateObservationRef",
    "CorrelateRequest",
    "CountMetricPayload",
    "DecomposeRequest",
    "DescriptorCardinality",
    "DetectRequest",
    "DetectTimeScope",
    "DiagnoseRequest",
    "DimensionCreateRequest",
    "DimensionDomainKind",
    "DimensionGroupingContract",
    "DimensionHeader",
    "DimensionHierarchySpec",
    "DimensionInterfaceContract",
    "DimensionListItem",
    "DimensionListResponse",
    "DimensionListResponseFull",
    "DimensionResponse",
    "DimensionUpdateRequest",
    "DimensionValueDomainSpec",
    "DimensionValueType",
    "DomainCatalogCreateRequest",
    "DomainCatalogListResponse",
    "DomainCatalogResponse",
    "DomainCatalogStatus",
    "DomainCatalogUpdateRequest",
    "DomainSemanticObjectSearchItem",
    "DomainSemanticObjectSearchResponse",
    "DistributionMetricPayload",
    "DistributionSpec",
    "DatasourceDeleteResponse",
    "DatasourcePolicyPayload",
    "DatasourcePolicyResponse",
    "DatasourceRegisterRequest",
    "DatasourceResponse",
    "DatasourceUpdateRequest",
    "EntityKind",
    "EntityRelationshipCreateRequest",
    "EntityRelationshipListItem",
    "EntityRelationshipListResponse",
    "EntityRelationshipResponse",
    "EntityRelationshipUpdateRequest",
    "EntityBindingSpec",
    "EntityFieldSpec",
    "EntityHeader",
    "EntityHierarchySpec",
    "EntityIdentitySpec",
    "EntityInterfaceContract",
    "EntityProcessContract",
    "PhysicalExpressionLocatorSpec",
    "EnumSetCreateRequest",
    "EnumSetHeader",
    "EnumSetListItem",
    "EnumSetListResponse",
    "EnumSetResponse",
    "EnumSetUpdateRequest",
    "EnumSetVersionResponse",
    "EnumSetVersionSpec",
    "EnumValueSpec",
    "EnumValueType",
    "ExperimentContextPayload",
    "ExperimentSplitBasis",
    "ExperimentVariant",
    "FieldBinding",
    "FieldProfileRequirement",
    "FieldSurfaceSpec",
    "ForecastRequest",
    "GovernancePreflightRequirement",
    "FunnelDefinitionPayload",
    "GovernanceCheckRequest",
    "HierarchyType",
    "HorizonSpec",
    "HypothesisContract",
    "IdStability",
    "IdleGapSpec",
    "InferentialSampleSummary",
    "IntentTestRequest",
    "JobSubmitRequest",
    "JoinKind",
    "JoinRelation",
    "LifecycleStateMachinePayload",
    "LifecycleStatus",
    "ListResponseBase",
    "Measure",
    "MeasurementComponent",
    "MembershipCardinality",
    "MetricFamily",
    "MetricHeader",
    "MetricPayload",
    "MetricQueryStep",
    "ModifyStepOperation",
    "NullabilityPolicy",
    "NullableKeyPolicy",
    "ObjectHeaderBase",
    "ObjectListItemBase",
    "ObjectResponseBase",
    "ObjectStatus",
    "ObservationRef",
    "ObserveRequest",
    "ObserveScope",
    "ObserveTimeScope",
    "ObserveTimeScopeAsOf",
    "ObserveTimeScopeLatestAvailable",
    "ObserveTimeScopeRange",
    "ObserveTimeScopeSnapshotNow",
    "OwnershipSemantics",
    "PartitionPruningOverride",
    "PathLagSpec",
    "PathPatternPayload",
    "PlanPatchRequest",
    "PolicyCreateRequest",
    "PolicyUpdateRequest",
    "PopulationSpec",
    "PredicateAtom",
    "PredicateConjunction",
    "PredicateCreateRequest",
    "PredicateHeader",
    "PredicateInterfaceContract",
    "PredicateListItem",
    "PredicateListResponse",
    "PredicateListResponseFull",
    "PredicateOperator",
    "PredicatePayload",
    "PredicateResponse",
    "PredicateUpdateRequest",
    "PredicateTimePolicy",
    "PredicateUsage",
    "ProcessCapability",
    "ProcessInterfaceContract",
    "ProcessObjectCreateRequest",
    "ProcessObjectHeader",
    "ProcessObjectListItem",
    "ProcessObjectListResponse",
    "ProcessObjectListResponseFull",
    "ProcessObjectResponse",
    "ProcessObjectUpdateRequest",
    "ProcessPayload",
    "ProcessRequirement",
    "ProfileAggregationCompatibility",
    "ProfileGrainCompatibility",
    "ProfileTimeCompatibility",
    "ProcessType",
    "ProfileKind",
    "ProfileSchemaVersion",
    "ProfileSubjectKind",
    "ProfileTrace",
    "QualityRuleCreateRequest",
    "RateMetricPayload",
    "ReadinessSignal",
    "ReadinessStatus",
    "RepeatedValuePolicy",
    "RelationshipGrainCompatibility",
    "RelationshipKeyAlignment",
    "RelationshipTimeAlignment",
    "RouteCapabilityProfileResponse",
    "RouteEngineResponse",
    "RouteIntentRequest",
    "RouteResolveRequest",
    "RouteResolveResponse",
    "SampleKind",
    "Scope",
    "ScoreMetricPayload",
    "SemanticRef",
    "SemanticBatchItem",
    "SemanticBatchItemResponse",
    "SemanticBatchRequest",
    "SemanticBatchResponse",
    "SemanticValidateActionResponse",
    "SemanticValidationSummary",
    "SemanticRole",
    "SessionContractPayload",
    "SessionCreateRequest",
    "SessionStateQueryRequest",
    "SessionTerminateRequest",
    "SnapshotEffectiveWindowAlignment",
    "SourceObjectResponse",
    "StableDescriptorSpec",
    "StateSpec",
    "StepGapSpec",
    "StepSpec",
    "StructureKind",
    "SubjectCardinality",
    "SumMetricPayload",
    "SurvivalMetricPayload",
    "SurvivalSpec",
    "SyncSelectionItem",
    "SyncSelectionRequest",
    "TargetKind",
    "TestObservationRef",
    "TimeAxis",
    "TimeCreateRequest",
    "TimeDerivedRequirementSpec",
    "TimeGranularity",
    "TimeListItem",
    "TimeListResponse",
    "TimeListResponseFull",
    "TimeResponse",
    "TimeScope",
    "TimeSemanticHeader",
    "TimeSemanticRole",
    "TimeSurfaceSpec",
    "TimeUpdateRequest",
    "TimeWindow",
    "BindingCoverageAddition",
    "BindingDeriveRevisionRequest",
    "TypedBindingCreateRequest",
    "TypedBindingListItem",
    "TypedBindingListResponse",
    "TypedBindingResponse",
    "TypedBindingUpdateRequest",
    "TypedEntityCreateRequest",
    "TypedEntityListItem",
    "TypedEntityListResponse",
    "TypedEntityListResponseFull",
    "TypedEntityResponse",
    "TypedEntityUpdateRequest",
    "TypedMetricCreateRequest",
    "MetricRevisionCreateRequest",
    "TypedMetricListItem",
    "TypedMetricListResponse",
    "TypedMetricListResponseFull",
    "TypedMetricResponse",
    "TypedMetricUpdateRequest",
    "UniquenessScope",
    "ValidateHypothesis",
    "ValidateObservationInput",
    "ValidateRequest",
    "ValueSemantics",
    "WindowOffset",
    "WindowSpec",
    "validate_contract_version",
    "validate_ref_prefix",
]
