"""Semantic layer API models.

This package provides Pydantic models for the Marivo HTTP API.

Modules:
- base: Shared types, validators, and base classes
- marivo_extensions: MARIVO extension models
- intent_request_models: Typed intent request models (observe, compare, detect, etc.)
- intent_response_models: Typed intent response models
- session: Session management request models
- calendar: Calendar data models
- _infrastructure: Infrastructure configuration models (datasource, routing, etc.)
"""

# Infrastructure models (datasource, routing, steps, signals, etc.)
# OSI core models
from marivo.contracts.generated import (
    CustomExtension,
    Dataset,
    DialectExpression,
    Dimension,
    Expression,
    Field,
    Metric,
    OSIDocument,
    Relationship,
    SemanticModel,
)
from marivo.contracts.generated.osi import (
    MarivoDatasetCustomExtension,
    MarivoMetricCustomExtension,
)

from ._infrastructure import (
    AggregateQueryStep,
    AnalysisTimeOverride,
    AttributeChangeStep,
    BrowseSchemaItem,
    BrowseTableItem,
    DatasourceColumnResponse,
    DatasourceDeleteResponse,
    DatasourceRegisterRequest,
    DatasourceResponse,
    DatasourceUpdateRequest,
    DuckDbDatasourceConnection,
    ExecutionLocatorEntry,
    Measure,
    MetricQueryStep,
    ModifyStepOperation,
    ObjectPropertiesResponse,
    PartitionPruningOverride,
    PlanPatchRequest,
    ReadinessSignal,
    RouteCapabilityProfileResponse,
    RouteEngineResponse,
    RouteIntentRequest,
    RouteResolveRequest,
    RouteResolveResponse,
    RoutingCandidate,
    RoutingDetail,
    RoutingSourceSummary,
    Scope,
    TablePreviewColumn,
    TablePreviewResponse,
    TimeAxis,
    TimeScope,
    TimeWindow,
    TrinoDatasourceConnection,
)
from .base import (
    AggregationMethod,
    AggregationScope,
    # Base models
    ApiErrorDetail,
    BindingRole,
    BindingScope,
    BlockingRequirement,
    Cardinality,
    CardinalityToParent,
    CarrierKind,
    CatalogMetadata,
    ConsumptionBehavior,
    ConsumptionPolicyType,
    ContextKind,
    ContractMode,
    DescriptorCardinality,
    DimensionDomainKind,
    DimensionValueType,
    DomainCatalogStatus,
    EntityKind,
    EnumValueType,
    HierarchyType,
    HorizonSpec,
    IdStability,
    JoinKind,
    LifecycleStatus,
    ListResponseBase,
    MembershipCardinality,
    NullabilityPolicy,
    NullableKeyPolicy,
    ObjectHeaderBase,
    ObjectListItemBase,
    ObjectResponseBase,
    ObjectStatus,
    OwnershipSemantics,
    PopulationSpec,
    PredicateOperator,
    PredicateTimePolicy,
    PredicateUsage,
    ProcessType,
    ProfileKind,
    ProfileSchemaVersion,
    ProfileSubjectKind,
    ReadinessStatus,
    RepeatedValuePolicy,
    SemanticRef,
    SemanticRole,
    SemanticValidateActionResponse,
    SemanticValidationSummary,
    StateSpec,
    StepSpec,
    StructureKind,
    SubjectCardinality,
    TargetKind,
    TimeGranularity,
    TimeSemanticRole,
    # Literal types
    UniquenessScope,
    ValueSemantics,
    WindowOffset,
    WindowSpec,
    validate_contract_version,
    # Validators
    validate_ref_prefix,
)

# Calendar models
from .calendar import (
    CalendarDataLoadRequest,
    CalendarDataLoadResponse,
    CalendarDataRow,
    CalendarVersionItem,
)

# Intent API models
from .intent_request_models import (
    AttributeObservationInput,
    AttributeRequest,
    DetectTimeScope,
    DiagnoseRequest,
    ObserveScope,
    ObserveTimeScope,
    ObserveTimeScopeAsOf,
    ObserveTimeScopeLatestAvailable,
    ObserveTimeScopeRange,
    ObserveTimeScopeSnapshotNow,
)
from .intent_response_models import (
    AttributeResponse,
    DiagnoseResponse,
    IntentPayload,
)
from .json_contract import (
    EmptyObject,
    JsonObject,
    JsonObjectMap,
    JsonScalar,
    JsonScalarMap,
    ScalarMap,
)

# MARIVO extension models
from .marivo_extensions import (
    MarivoDatasetExtension,
    MarivoFieldExtension,
    MarivoMetricExtension,
    MarivoMetricFilter,
    MarivoMetricFilterExpression,
    MarivoMetricFilterExpressionDialect,
    MarivoRelationshipExtension,
    MarivoSemanticModelExtension,
)

# Session models
from .session import (
    SessionBudget,
    SessionCreateRequest,
    SessionStateQueryRequest,
    SessionStateSlice,
    SessionTerminateRequest,
)
from .session_responses import (
    AnalysisSession,
    ArtifactRuntimeStatusResponse,
    PropositionContextView,
    PropositionRuntimeStatusResponse,
    SessionCreateResponse,
    SessionDetailResponse,
    SessionListResponse,
    SessionRuntimeStatusResponse,
    SessionStateView,
    SessionTerminateResponse,
)

__all__ = [  # noqa: RUF022
    "AggregateQueryStep",
    "AggregationMethod",
    "AggregationScope",
    "AnalysisSession",
    "AnalysisTimeOverride",
    "ApiErrorDetail",
    "ArtifactRuntimeStatusResponse",
    "AttributeChangeStep",
    "AttributeObservationInput",
    "AttributeRequest",
    "AttributeResponse",
    "BlockingRequirement",
    "BindingRole",
    "BindingScope",
    "BrowseSchemaItem",
    "BrowseTableItem",
    "CalendarDataRow",
    "CalendarDataLoadRequest",
    "CalendarDataLoadResponse",
    "CalendarVersionItem",
    "Cardinality",
    "CardinalityToParent",
    "CatalogMetadata",
    "CarrierKind",
    "ConsumptionBehavior",
    "ConsumptionPolicyType",
    "ContextKind",
    "ContractMode",
    "CustomExtension",
    "DatasourceDeleteResponse",
    "DatasourceColumnResponse",
    "DatasourceRegisterRequest",
    "DatasourceResponse",
    "DatasourceUpdateRequest",
    "Dataset",
    "DescriptorCardinality",
    "DetectTimeScope",
    "DiagnoseRequest",
    "DiagnoseResponse",
    "DialectExpression",
    "Dimension",
    "DimensionDomainKind",
    "DimensionValueType",
    "DomainCatalogStatus",
    "DuckDbDatasourceConnection",
    "EmptyObject",
    "EntityKind",
    "EnumValueType",
    "ExecutionLocatorEntry",
    "Expression",
    "Field",
    "HierarchyType",
    "HorizonSpec",
    "IdStability",
    "IntentPayload",
    "JoinKind",
    "JsonScalar",
    "JsonObject",
    "JsonObjectMap",
    "JsonScalarMap",
    "LifecycleStatus",
    "ListResponseBase",
    "MarivoDatasetCustomExtension",
    "MarivoDatasetExtension",
    "MarivoFieldExtension",
    "MarivoMetricCustomExtension",
    "MarivoMetricExtension",
    "MarivoMetricFilter",
    "MarivoMetricFilterExpression",
    "MarivoMetricFilterExpressionDialect",
    "MarivoRelationshipExtension",
    "MarivoSemanticModelExtension",
    "Measure",
    "MembershipCardinality",
    "Metric",
    "MetricQueryStep",
    "ModifyStepOperation",
    "NullabilityPolicy",
    "NullableKeyPolicy",
    "ObjectHeaderBase",
    "ObjectListItemBase",
    "ObjectPropertiesResponse",
    "ObjectResponseBase",
    "ObjectStatus",
    "ObserveScope",
    "ObserveTimeScope",
    "ObserveTimeScopeAsOf",
    "ObserveTimeScopeLatestAvailable",
    "ObserveTimeScopeRange",
    "ObserveTimeScopeSnapshotNow",
    "OSIDocument",
    "OwnershipSemantics",
    "PartitionPruningOverride",
    "PopulationSpec",
    "PredicateOperator",
    "PredicateTimePolicy",
    "PredicateUsage",
    "PlanPatchRequest",
    "ProcessType",
    "ProfileKind",
    "ProfileSchemaVersion",
    "ProfileSubjectKind",
    "PropositionContextView",
    "PropositionRuntimeStatusResponse",
    "ReadinessSignal",
    "ReadinessStatus",
    "Relationship",
    "RepeatedValuePolicy",
    "RouteCapabilityProfileResponse",
    "RouteEngineResponse",
    "RouteIntentRequest",
    "RouteResolveRequest",
    "RouteResolveResponse",
    "RoutingCandidate",
    "RoutingDetail",
    "RoutingSourceSummary",
    "ScalarMap",
    "Scope",
    "SemanticModel",
    "SemanticRef",
    "SemanticRole",
    "SemanticValidateActionResponse",
    "SemanticValidationSummary",
    "SessionBudget",
    "SessionCreateRequest",
    "SessionCreateResponse",
    "SessionDetailResponse",
    "SessionListResponse",
    "SessionRuntimeStatusResponse",
    "SessionStateQueryRequest",
    "SessionStateSlice",
    "SessionStateView",
    "SessionTerminateRequest",
    "SessionTerminateResponse",
    "StateSpec",
    "StepSpec",
    "StructureKind",
    "SubjectCardinality",
    "TablePreviewColumn",
    "TablePreviewResponse",
    "TargetKind",
    "TimeAxis",
    "TimeGranularity",
    "TimeScope",
    "TimeSemanticRole",
    "TimeWindow",
    "TrinoDatasourceConnection",
    "UniquenessScope",
    "ValueSemantics",
    "WindowOffset",
    "WindowSpec",
    "validate_contract_version",
    "validate_ref_prefix",
]
